var FormData = require('form-data');

export const adminWorkflowDataTemplate = (params: any) =>{
    var form = new FormData();

    form.setBoundary("--alteryx");
    form.append( 'file', params.file  as Buffer, params.name );
    form.append( 'owner', params.owner );
    form.append( 'name', params.name );
    form.append( 'validate', String(params.validate || false));
    form.append( 'isPublic', String(params.isPublic || false) );
    form.append( 'canDownload', String(params.canDownload || false ) );
    form.append( 'workerTag', params.workerTag || "");
    form.append( 'comments', params.comments || "Generated by Ayx Typescript SDK" );
    
    if (params.sourceAppId){
        form.append( 'sourceAppId', params.sourceAppId || "AYX CLI");
    }
    let data = form.getBuffer();
    return data;
}